#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "js$")
# ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nAuthor :: Riki Setiyo P.\nEmail :: Setiyoriki589@gmail.com"
printf "\nMake sure the coding is correct and check several times."
printf "\nStarted Validation\n"

for FILE in $STAGED_FILES
do
  eslint --quiet "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t$FILE \033[32mLOLOS\033[0m\n"
  else
    printf "\t$FILE \033[31mGAGAL\033[0m\n"
    PASS=false
  fi
done

printf "\nFinished\n\n"

if ! $PASS; then
printf "\033[0;31m"
  cat << "EOF"

// Sorry Please Correct Your Code\n,
//=================================================================
//
//  #####  #####    #####     #####   #####          ##  ##  ##
//  ##     ##  ##   ##  ##   ##   ##  ##  ##         ##  ##  ##
//  #####  #####    #####    ##   ##  #####          ##  ##  ##
//  ##     ##  ##   ##  ##   ##   ##  ##  ##
//  #####  ##   ##  ##   ##   #####   ##   ##        ##  ##  ##
//
//=================================================================


EOF
  printf "\033[0m"
  exit 1
else
  printf "\033[0;32m"
  cat << "EOF"
┈┈┈┈┈┈▕▔╲
┈┈┈┈┈┈┈▏▕
┈┈┈┈┈┈┈▏▕▂▂▂
▂▂▂▂▂▂╱┈▕▂▂▂▏
▉▉▉▉▉┈┈┈▕▂▂▂▏
▉▉▉▉▉┈┈┈▕▂▂▂▏
▔▔▔▔▔▔╲▂▕▂▂▂I

//====> @Copyright Setiyoriki589@gmail.com <============================
//
//   ####     #####    #####   ####              ##   #####   #####
//  ##       ##   ##  ##   ##  ##  ##            ##  ##   ##  ##  ##
//  ##  ###  ##   ##  ##   ##  ##  ##            ##  ##   ##  #####
//  ##   ##  ##   ##  ##   ##  ##  ##        ##  ##  ##   ##  ##  ##
//   ####     #####    #####   ####           ####    #####   #####
//
//======================================================================



EOF
  printf "\033[0m"
fi

exit $?
